### ISSUE TITLE
Inference does not work correctly

### ISSUE THREAD

**Issue by darkasevgen** [LeslieZhoa/DCT-NET.Pytorch#2]
Hi @LeslieZhoa, thanks for your implementation.
I tried running the [inference.py](https://github.com/LeslieZhoa/DCT-NET.Pytorch/blob/main/inference.py) script and I faced some problems.

I fixed the 'netG' key in the line:
https://github.com/LeslieZhoa/DCT-NET.Pytorch/blob/ebdc7bd5c7cff9a2dedcf2dd8f3630aa0ec303ce/inference.py#L25
to 'G' because final.pth does not contain 'netG'. 

Also in the postprocess method you make the slice [[..., ::-1]](https://github.com/LeslieZhoa/DCT-NET.Pytorch/blob/ebdc7bd5c7cff9a2dedcf2dd8f3630aa0ec303ce/inference.py#L32), and you also make it after calling the run method:
https://github.com/LeslieZhoa/DCT-NET.Pytorch/blob/ebdc7bd5c7cff9a2dedcf2dd8f3630aa0ec303ce/inference.py#L55

I removed the extra slice. 
But I still get an unrealistic image (ran at 1024 and 256 resolutions). I'm attaching an example (first line is 1024, second line is 256) and waiting for a response/comment.
![dct_net](https://user-images.githubusercontent.com/52633920/182562374-e707bbde-73d8-41e3-8854-ef171b62cd1b.png)

**Comment by LeslieZhoa** [comment]
Hi @darkasevgen ! Thanks for your question. I fix the slice bug and upload a new model. You can try again!

**Comment by darkasevgen** [comment]
Can you tell me more about how [gif](https://github.com/LeslieZhoa/DCT-NET.Pytorch/blob/main/assets/xcaq.gif) is received ?
Did you apply resize to a certain resolution and run the model? Or can the inference be done at any resolution?

**Comment by LeslieZhoa** [comment]
Hi @darkasevgen , the gif is generated with the whole image size. just like 
```py
img = cv2.imread('')
img_h,img_w,_ = img.shape 
n_h,n_w = img_h // 8 * 8,img_w // 8 * 8
img = cv2.resize(img,(n_w,n_h))
```
the model can run at any resolution which can be divided with no remainder.
but the result will be slightly worse.

**Comment by darkasevgen** [comment]
Thank you for your reply.
