### ISSUE TITLE
训练结果看起来不太正常

### ISSUE THREAD

**Issue by VERMANs** [LeslieZhoa/DCT-NET.Pytorch#6]
哈喽，大佬，我按照你的readme训练了自己的样式，但效果貌似不太令人满意，能告知我大概在哪出了问题吗
训练样式图：（1200张）
![image](https://user-images.githubusercontent.com/41277638/184269137-7533eead-4e78-430a-bef3-b33a431aae6d.png)
ccn训练了2000步
ttn训练了4w步的结果是：
![image](https://user-images.githubusercontent.com/41277638/184269362-65b042d8-1089-49e2-b6c7-95bece781fa7.png)
![image](https://user-images.githubusercontent.com/41277638/184269399-d6382197-09e7-4d28-a5e3-8456156bb9d2.png)

**Comment by LeslieZhoa** [comment]
Hi @VERMANs  首先你的ttn的风格数据似乎是有点少，论文里是1w张生成+真实的风格图
你的ttn训练的时候的真实图片是经过align和crop的人脸吗？你的ttn做inference的时候如果只是针对人脸部分会好一些吗？如果这些都没有问题的话，尝试着加大batch（分布式训练，增加节点数），增加迭代次数，调整一下损失函数的比重，也许会有不错的结果
祝你好运！

**Comment by VERMANs** [comment]
Hi @LeslieZhoa 非常感谢你的回复，不好意思，我上面表达可能有误，我在ttn训练时的风格数据是生成的2w风格图（没有用到真实的风格图，这操作对的吗），
ttn训练的真实图片是经过align和crop的人脸，如下所示
![image](https://user-images.githubusercontent.com/41277638/184281140-e1ebe30b-6288-40d2-9292-ee7f5983708b.png)
在ttn只对人脸效果也并不理想（且是训练集的人脸），效果如下
![image](https://user-images.githubusercontent.com/41277638/184281437-717e9921-c129-4f0a-8d2f-d261b18a3e30.png)
对于你的建议，我会尝试，后续有结果，我会及时跟你反馈！

**Comment by LeslieZhoa** [comment]
@VERMANs  ttn的风格数据是要再经过人工筛选的，不知道你是不是有操作这一步

**Comment by VERMANs** [comment]
@LeslieZhoa  是的，我因为偷懒没做这步，可是这步是需要从2w张人工挑选5000-1w张吗，我想知道这里面好坏的标准大概是什么？

**Comment by LeslieZhoa** [comment]
> @LeslieZhoa 是的，我因为偷懒没做这步，可是这步是需要从2w张人工挑选5000-1w张吗，我想知道这里面好坏的标准大概是什么？

@VERMANs 纯主观判断，就是你觉得该图片生成的风格可以接受就ok

**Comment by VERMANs** [comment]
@LeslieZhoa  好的，非常感谢，我在尝试，有结果第一时间与你反馈

**Comment by VERMANs** [comment]
你好 @LeslieZhoa 
下面是结果，（图片依次为：测试图片1，测试结果1，测试图片2，测试结果2，风格图样例1，风格图样例2）
![image](https://user-images.githubusercontent.com/41277638/185523384-06d1cf2d-aa41-4e0c-b36c-1ccc0648d124.png)
请问这个效果是正确的吗？关于测试结果2，他衣服的颜色风格是否来源于样式图中人像以外的白色背景呢？
期待你的回复，愿你万事如意

**Comment by LeslieZhoa** [comment]
@VERMANs 我感觉是你的风格图片全是偏白色背景，导致模型无法学习风格化的背景，所以脸部周围会有些artifacts，衣服颜色会变成白色。一点小建议，如果想继续沿用这种风格的话，随意找一些正常背景图片，加上opengl的lut处理，再和分割后的风格人脸进行拼接，这样训练也许会对背景生成有帮助。
祝你好运！

**Comment by watertianyi** [comment]
@VERMANs Is image pairing required during training?
